#!/usr/bin/env python3
"""
run_analysis.py - Run static analysis tools (cppcheck, MSVC /analyze, lizard)
and generate a unified Markdown report in the 'analysis/' folder.
"""

import subprocess
import sys
import os
from pathlib import Path
from datetime import datetime

# ----------------------------------------------------------------------
# Configuration
# ----------------------------------------------------------------------
PROJECT_ROOT = Path.cwd()
SRC_DIR = PROJECT_ROOT / "src"
GENERATED_DIR = SRC_DIR / "generated"
MAIN_CPP = PROJECT_ROOT / "main.cpp"
ANALYSIS_DIR = PROJECT_ROOT / "analysis"

# Ensure analysis directory exists
ANALYSIS_DIR.mkdir(exist_ok=True)

# ----------------------------------------------------------------------
# Tool runners
# ----------------------------------------------------------------------
def run_cppcheck():
    """Run cppcheck on the codebase."""
    print("🔍 Running cppcheck...")
    # Build file list: all .h and .cpp in src, plus main.cpp
    files = []
    if SRC_DIR.exists():
        files.extend(SRC_DIR.rglob("*.h"))
        files.extend(SRC_DIR.rglob("*.cpp"))
    files.append(MAIN_CPP)

    if not files:
        return False, "No source files found.", ""

    cmd = [
        "cppcheck",
        "--enable=warning,performance,portability",
        "--suppress=missingIncludeSystem",
        "--suppress=unmatchedSuppression",  # avoid noise
        "-I", str(SRC_DIR),
        "-I", str(GENERATED_DIR),
        *[str(f) for f in files]
    ]

    try:
        result = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            timeout=120
        )
        success = (result.returncode == 0)
        return success, result.stdout, result.stderr
    except FileNotFoundError:
        return False, "", "cppcheck not found. Please install it (winget install Cppcheck.Cppcheck)."
    except subprocess.TimeoutExpired:
        return False, "", "cppcheck timed out after 120 seconds."

def run_msvc_analyze():
    """Run MSVC /analyze on main.cpp."""
    print("🔍 Running MSVC /analyze...")

    # Use the same flags as in debug_analysis.py
    flags = [
        "cl.exe",
        "/analyze",
        "/analyze:quiet-",          # show all output even with no warnings
        "/D_DEBUG",
        "/Zi",
        "/EHsc",
        "/MDd",
        "/nologo",
        "/I", str(SRC_DIR),
        "/I", str(GENERATED_DIR),
        "/Fe:analyze.exe",
        str(MAIN_CPP)
    ]

    try:
        result = subprocess.run(
            flags,
            capture_output=True,
            text=True,
            timeout=60
        )
        success = (result.returncode == 0)
        return success, result.stdout, result.stderr
    except FileNotFoundError:
        return False, "", "cl.exe not found. Make sure you are in a Visual Studio developer command prompt."
    except subprocess.TimeoutExpired:
        return False, "", "MSVC analysis timed out after 60 seconds."

def run_lizard():
    """Run lizard complexity analysis."""
    print("🔍 Running lizard...")

    cmd = [
        "lizard",
        str(SRC_DIR),
        str(MAIN_CPP),
        "-l", "cpp",
        "-C", "15",          # warn on complexity > 15
        "-L", "200"         # warn on length > 200
    ]

    try:
        result = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            timeout=60
        )
        success = (result.returncode == 0)
        return success, result.stdout, result.stderr
    except FileNotFoundError:
        return False, "", "lizard not found. Install with: python -m pip install lizard"
    except subprocess.TimeoutExpired:
        return False, "", "lizard timed out after 60 seconds."

# ----------------------------------------------------------------------
# Markdown report generator
# ----------------------------------------------------------------------
def generate_report(cppcheck, msvc, lizard):
    """Write a combined markdown report."""
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    report_lines = []

    # Header
    report_lines.append(f"# Static Analysis Report - {timestamp}\n")
    report_lines.append("Generated by `run_analysis.py`\n")
    report_lines.append("---\n")

    # Cppcheck section
    report_lines.append("## 🔍 Cppcheck\n")
    cppcheck_success, cppcheck_out, cppcheck_err = cppcheck
    report_lines.append(f"- **Status:** {'✅ Success' if cppcheck_success else '❌ Failed'}\n")
    if cppcheck_out.strip():
        report_lines.append("\n**Standard output:**\n")
        report_lines.append("```\n" + cppcheck_out.strip() + "\n```\n")
    if cppcheck_err.strip():
        report_lines.append("\n**Standard error:**\n")
        report_lines.append("```\n" + cppcheck_err.strip() + "\n```\n")
    report_lines.append("---\n")

    # MSVC /analyze section
    report_lines.append("## 🛠️ MSVC /analyze\n")
    msvc_success, msvc_out, msvc_err = msvc
    report_lines.append(f"- **Status:** {'✅ Success' if msvc_success else '❌ Failed'}\n")
    # Filter out the compilation banner and keep only warnings/errors
    filtered_out = []
    for line in msvc_out.splitlines():
        if "analyze.exe" not in line and "Microsoft (R)" not in line and "Copyright" not in line:
            filtered_out.append(line)
    if filtered_out:
        report_lines.append("\n**Analysis output:**\n")
        report_lines.append("```\n" + "\n".join(filtered_out) + "\n```\n")
    if msvc_err.strip():
        report_lines.append("\n**Standard error:**\n")
        report_lines.append("```\n" + msvc_err.strip() + "\n```\n")
    report_lines.append("---\n")

    # Lizard section
    report_lines.append("## 🦎 Lizard (Complexity)\n")
    lizard_success, lizard_out, lizard_err = lizard
    report_lines.append(f"- **Status:** {'✅ Success' if lizard_success else '❌ Failed'}\n")
    if lizard_out.strip():
        report_lines.append("\n**Complexity report:**\n")
        report_lines.append("```\n" + lizard_out.strip() + "\n```\n")
    if lizard_err.strip():
        report_lines.append("\n**Standard error:**\n")
        report_lines.append("```\n" + lizard_err.strip() + "\n```\n")
    report_lines.append("---\n")

    # Write file
    report_path = ANALYSIS_DIR / f"analysis_{datetime.now().strftime('%Y%m%d_%H%M%S')}.md"
    report_path.write_text("\n".join(report_lines), encoding="utf-8")
    print(f"✅ Report written to {report_path}")

# ----------------------------------------------------------------------
# Main
# ----------------------------------------------------------------------
def main():
    print("=== Running static analysis suite ===\n")

    cppcheck_result = run_cppcheck()
    msvc_result = run_msvc_analyze()
    lizard_result = run_lizard()

    generate_report(cppcheck_result, msvc_result, lizard_result)

    print("\n=== Analysis complete ===")

if __name__ == "__main__":
    main()