#!/usr/bin/env python3
"""
Generate inline functions for config_ini_io.h
"""

import re

def generate_config_functions():
    """Generate config_functions.h with inline functions"""
    
    # Read the current src/config_ini_io.h
    with open('src/config_ini_io.h', 'r') as f:
        content = f.read()
    
    # Parse the ConfigData struct
    pattern = r'typedef\s+struct\s*\{([^}]+)\}\s*ConfigData\s*;'
    match = re.search(pattern, content, re.DOTALL)
    
    if not match:
        print("Error: Could not find ConfigData struct in src/config_ini_io.h")
        return
    
    struct_body = match.group(1)
    
    # Extract fields
    fields = []
    lines = struct_body.strip().split('\n')
    for line in lines:
        line = line.strip().rstrip(';')
        if not line or line.startswith('//'):
            continue
        
        # Split by commas to handle multiple fields per line
        parts = line.split()
        if len(parts) >= 2:
            type_name = parts[0]
            var_names = ' '.join(parts[1:])
            
            for var_part in var_names.split(','):
                var_part = var_part.strip()
                if var_part:
                    fields.append((type_name, var_part))
    
    print(f"Found {len(fields)} fields: {[name for _, name in fields]}")
    
    # Generate SaveConfig format string and arguments
    format_parts = []
    arg_lines = []
    
    for type_name, var_name in fields:
        # Determine format specifier
        if 'float' in type_name:
            fmt = '%f'
        elif 'double' in type_name:
            fmt = '%lf'
        elif type_name == 'bool':
            fmt = '%d'
        elif type_name.startswith('uint') or type_name == 'unsigned':
            fmt = '%u'
        elif type_name.startswith('int') or type_name == 'int':
            fmt = '%d'
        elif 'char' in type_name and '*' in type_name:
            fmt = '%s'
        else:
            fmt = '%d'  # Default
            
        format_parts.append(f"{var_name}={fmt}")
        arg_lines.append(f"config->{var_name}")
    
    format_string = '\\n'.join(format_parts) + '\\n'
    args_string = ', '.join(arg_lines)
    
    # Generate parsing blocks for LoadConfig
    parse_blocks = []
    
    for i, (type_name, var_name) in enumerate(fields):
        length = len(var_name) + 1  # +1 for '='
        
        # Determine parser function
        if 'float' in type_name or 'double' in type_name:
            parser = 'SDL_atof'
        else:
            parser = 'SDL_atoi'  # Works for int, bool, unsigned
        
        # First block uses "if", rest use "else if"
        if i == 0:
            parse_blocks.append(f'        if (SDL_strncmp(line, "{var_name}=", {length}) == 0) {{')
        else:
            parse_blocks.append(f'        }} else if (SDL_strncmp(line, "{var_name}=", {length}) == 0) {{')
        
        parse_blocks.append(f'            config->{var_name} = {parser}(line + {length});')
    
    # Close the last block
    if parse_blocks:
        parse_blocks.append('        }')
    
    parse_logic = '\n'.join(parse_blocks)
    
    # Write to config_functions.h
    functions_content = f"""/* Generated by gen_config_functions.py - DO NOT EDIT MANUALLY */
#pragma once
#include <SDL3/SDL.h>

/* Inline function to generate the config string */
static inline void Generated_SaveConfigToString(ConfigData* config, char* buffer, size_t buffer_size) {{
    SDL_snprintf(buffer, buffer_size, 
                 "{format_string}", 
                 {args_string});
}}

/* Inline function to parse config from string data */
static inline void Generated_LoadConfigFromString(ConfigData* config, char* data) {{
    char* line = data;
    while (*line) {{
{parse_logic}
                
        while (*line && *line != '\\n') line++;
        if (*line == '\\n') line++;
    }}
}}
"""
    
    with open('src/generated/config_functions.h', 'w') as f:
        f.write(functions_content)
    
    print("\nGenerated config_functions.h successfully!")
    print("Include this file in your config_ini_io.h and call the generated functions.")

if __name__ == "__main__":
    generate_config_functions()